### ISSUE TITLE
Deadlock 해결 방안 필요

### ISSUE THREAD

**Issue by ssjjaa-algo** [kksjae-hyyejji/Payment-System#5]
1. JPA의 commit 단위를 파악해야 합니다.

2. repository 별로 commit을 분리해야(?) 하는 것 같다는 생각이 듭니다..

**Comment by LimHyeji** [comment]
JPA는 Transactional 어노테이션을 통해 메소드 단위의 커밋이 이루어지며, 행 단위의 락이 걸립니다.

행 단위의 락으로 인해 데드락이 발생했다고 판단했으며, Lock 어노테이션을 통해 락의 단위를 엔티티로 높임으로써 해결되었습니다.

낙관락과 비관락에 대해 공부할 필요가 있습니다.
